<?php
if(!defined('THINK_PATH')) exit();
return $array = array (
  'DB_TYPE' => 'mysql',
  'DB_HOST' => 'localhost',
  'DB_NAME' => 'jiaqun',
  'DB_USER' => 'root',
  'DB_PWD' => 'root',
  'DB_PORT' => 3306,
  'DB_PREFIX' => 'yufu_wx_',
  'DB_BACKUP' => '../Data/backup',
  'RBAC_ROLE_TABLE' => 'yufu_wx_role',
  'RBAC_USER_TABLE' => 'yufu_wx_user',
  'RBAC_ACCESS_TABLE' => 'yufu_wx_access',
  'RBAC_NODE_TABLE' => 'yufu_wx_node',
  'URL_CASE_INSENSITIVE' => true,
  'URL_MODEL' => 0,
  'DEFAULT_THEME' => 'qun',
  'WX_TOKEN' => '',
  'SITE_NAME' => '加群网',
  'SITE_TITLE' => '微信群大全,微信群二维码,微信群500人大群,微信群发布,二维码发布与分享',
  'SITE_KEYWORDS' => '微信群 公众平台 公众号推广 微信二维码 二维码分享 微商涨粉',
  'SITE_DESCRIPTION' => '微信群发布,二维码发布与分享微信群大全,微信群二维码,微信群500人大群，面向草根站长，做网站，更简单。',
  'RMB_CHANGE_INTERGRAL' => 5,
  'ISCOMMENT' => 1,
  'COMMENTTYPE' => 1,
  'ISADDACCOUNT' => 0,
  'XFINTERGRAL' => 2,
  'ZSINTERGRAL' => 17,
  'ISAUTOVERIFY' => 0,
  'YUFUMARK' => '',
  'ISTASK' => 0,
  'TASKURL' => '',
);
?>